services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/ssl:/etc/ssl
    depends_on:
      - frontend
      - go_api
      - python_api

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: voicediary_user
      POSTGRES_PASSWORD: voicediary_password
      POSTGRES_DB: voicedb
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    env_file: ".env"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "80:80"
    command: nginx -g "daemon off;"

  go_api:
    env_file: ".env"
    build:
      context: ./backend/go_api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://voicediary_user:voicediary_password@db:5432/voicedb?sslmode=disable
    volumes:
      - ./backend/go_api:/app
    ports:
      - "8080:8080"
    command: ./go_api

  python_api:
    env_file: ".env"
    build:
      context: ./backend/python_api
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: uvicorn backend.python_api.app:app --host python_api --port 5000 --log-level debug

volumes:
  pgdata:
