definitions:
  handler.InsightsResponse:
    properties:
      dictionary:
        additionalProperties: true
        type: object
    type: object
  handler.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  handler.RegisterRequest:
    properties:
      login:
        type: string
      nickname:
        type: string
      password:
        type: string
    required:
    - login
    - nickname
    - password
    type: object
  repository.Record:
    properties:
      emotion:
        type: string
      feedback:
        type: string
      record_date:
        type: string
      record_id:
        type: integer
      summary:
        type: string
      user_id:
        type: integer
    type: object
  repository.User:
    properties:
      id:
        type: integer
      login:
        type: string
      nickname:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /records/{recordID}:
    get:
      description: Returns emotion and summary for a specific record.
      parameters:
      - description: Record ID
        in: path
        name: recordID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.Record'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get analysis result for a record.
      tags:
      - records
  /records/insights:
    post:
      description: Returns insights for a specific record.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.InsightsResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get insights for a record.
      tags:
      - records
  /records/upload:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a voice file, sends it to the ML service for analysis,
        and saves the record.
      parameters:
      - description: User ID
        in: formData
        name: userID
        required: true
        type: integer
      - description: Voice file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload  a new voice record
      tags:
      - records
  /users/{userID}/records:
    get:
      consumes:
      - application/json
      description: Returns a list of all diary records for a specific user.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repository.Record'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user records
      tags:
      - records
  /users/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login a user
  /users/logout:
    post:
      description: Logs out the user by deleting the session token.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Logout a user
  /users/me:
    get:
      description: Returns the current user's info based on the session token.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get current user info
  /users/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
swagger: "2.0"
