name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache-dependency-path: backend/go_api/go.sum
      - name: Test with the Go CLI
        run: go test ./backend/go_api
